### ISSUE TITLE
[Feature] I could be cool to be able to choose the primary color.

### ISSUE THREAD

**Issue by alexcamlo** [Aliqyan-21/darkvoid.nvim#3]
I really like the minimalist of the color scheme and the good taste using it but green doesn't go with all my computer theme.
I could be cool to be able to pass a `main_color` in the configuration and it would generate the shades/variants.

**Comment by Aliqyan-21** [comment]
Thank you for suggesting this feature thewinger, we will definitely think about it and implement it in our next update...will it be good for you?
Do you have any suggestions on how we can implement it?

**Comment by Aliqyan-21** [comment]
So, Mr. thewinger Thank you for your feedback. I understand the desire to dynamically change theme colors. However, the flexibility of our theme allows you to manually adjust the colors according to your preferences and computer themes. Here's why this approach can be advantageous:

Full Customization: The theme’s configuration file (colors.lua) is designed to be fully customizable. This means you can change all colors, including those of specific groups, to match any color scheme you prefer.

Fine-Tuned Control: By manually editing the color settings, you gain precise control over each aspect of the theme, ensuring it perfectly matches your personal aesthetic or the specific theme of your computer.

Simplicity and Flexibility: Manual customization simplifies the process, allowing users to easily tweak individual colors without needing to understand or implement complex algorithms for color generation.

And thus sir I will suggest you to tweak the configuration according your computer themes colors as in that way you will be able to achieve the best result as I tried to implement the algorithm to do so and it resulted in not perfect colors that you can choose by your hand(handpicked).

Thank You and have a nice day!

**Comment by alexcamlo** [comment]
Thank you for trying, it makes total sense what you explained.
