### ISSUE TITLE
Port to another editors and applications?

### ISSUE THREAD

**Issue by zoedsoupe** [Aliqyan-21/darkvoid.nvim#4]
Do you have any interest in porting this theme to another editors like zed, helix or other applications like warp and kitty terminal?

I tried to to this port and already did it for the following ones:
- [zed editor](https://zed.dev)
- [helix editor](https://docs.helix-editor.com)
- [warp terminal](https://warp.dev)

so i mean, is that ok for you? does it make sense to open a PR with this additions? maybe create another repos? wdyt?

**Comment by zoedsoupe** [comment]
and really thank you for this theme! it turned into my daily driver and isn't aggressive to my eyes even in the morning!

**Comment by Aliqyan-21** [comment]
Wow never thought of porting darkvoid to other editors or terminals but nice idea in this way we can make a whole ecosystem with this color scheme.

For now I don't think adding these in this repo will be a great idea right, but you can make seperate repos with this colorscheme for porting to other applications, and then we can make a common repo which will have link to all those repos for different terminals and editors, what do you think?

Just like some other themes like [catpuccin](https://github.com/catppuccin/catppuccin) ?

**Comment by Aliqyan-21** [comment]
> and really thank you for this theme! it turned into my daily driver and isn't aggressive to my eyes even in the morning!

Hey @zoedsoupe you know what? Thanks this made my day 😁❤️

**Comment by zoedsoupe** [comment]
yeah, just like catppuccin haha! sure! i'll open these repos and i'll let you know! 💜

**Comment by Aliqyan-21** [comment]
Haha, yes sure @zoedsoupe all the best!

**Comment by windowsrefund** [comment]
Rather than chase after each and every thing individually, I'd suggest it would be better to create a base16 and/or base24 [colorscheme](https://github.com/tinted-theming/schemes) since it could then be used by [tinty](https://github.com/tinted-theming/tinty)

**Comment by zoedsoupe** [comment]
yeah it can make sense, but that way you kinda lock theme usage to tiny (for better experience) or depends on base16/24 support, which some apps do not handle

also, porting a theme to base16/24 at least with my experience makes the porting, specially for editor (aka treessiter) kinda difficult while losing some colors, but i'm being biased here so you can just ignore this last paragraph

**Comment by zoedsoupe** [comment]
hey @Aliqyan-21 does you mind to create a GitHub org for this? i think it's better than a single "centralized" repo

with an org everyone could collaborate too (:

i can create it too, but i think as you are the main author, it should be your responsibility

wdyt?

**Comment by zoedsoupe** [comment]
zed theme probably need some enhancement but helix and warp themes are working like a charm, as i'm using it as my daily driver

**Comment by zoedsoupe** [comment]
@Aliqyan-21 here we go:

## helix version

<img width="1002" alt="image" src="https://github.com/user-attachments/assets/da0987e5-0fc9-4c32-9b03-cc2253aeb905">

source: https://github.com/zoedsoupe/dark-void-helix

## zed version

<img width="1335" alt="image" src="https://github.com/user-attachments/assets/f80d291a-5d3d-4a84-976f-ccdae61f7a1a">

source: https://github.com/zoedsoupe/darkvoid-zed

**Comment by Aliqyan-21** [comment]
Wow looks cool @zoedsoupe!

So you really want a github org? Should we do it? And if yes what should we name it?😁

**Comment by zoedsoupe** [comment]
in my opinion is an easier way to other people contribute and manage different port "authors". it's also a way to centralize the contribution docs and the semantics of the theme

i think the name can be darkvoid-theme or even only darkvoid like the [catppuccin](https://github.com/catppuccin) one. wdyt?

**Comment by Aliqyan-21** [comment]
Yes okay @zoedsoupe Darkvoid was what I was thinking too

**Comment by Aliqyan-21** [comment]
But Darkvoid is taken

**Comment by Aliqyan-21** [comment]
How about Darkvoid-Theme?

**Comment by zoedsoupe** [comment]
that's ok, no problem

**Comment by zoedsoupe** [comment]
i'll move the repositories for it

**Comment by Aliqyan-21** [comment]
> i'll move the repositories for it

yes sure @zoedsoupe

**Comment by zoedsoupe** [comment]
think we can close it rn
