### ISSUE TITLE
Colorscheme does not work well if it is not the only colorscheme installed

### ISSUE THREAD

**Issue by gustavkrist** [Aliqyan-21/darkvoid.nvim#6]
I like this colorscheme, but I tend to switch between colorschemes and unlike every other colorscheme I have installed, this one only seems to work properly if it is used as the only colorscheme. Other colorschemes only extend the config when their setup method is called and then apply them when the colorscheme is loaded using `colorscheme <name>`, which allows adding multiple colorschemes to for example a lazy plugin spec and setting them all up.
Calling `colorscheme darkvoid` after another colorscheme has been set also does not work proplerly as highlights are not cleared when darkvoid is applied.
I made a small fix for these issued so that I could use the colorscheme and have opened a PR https://github.com/Aliqyan-21/darkvoid.nvim/pull/7, as I think this would benefit more people.

**Comment by Aliqyan-21** [comment]
Hello @gustavkrist, thanks for finding this bug and fixing this issue, I have merged your PR as it makes the colorscheme more flexible and helps for the seamless transition between different colorschemes!
