### ISSUE TITLE
nvim-cmp and Which-key

### ISSUE THREAD

**Issue by windowsrefund** [Aliqyan-21/darkvoid.nvim#8]
I really like the direction of this theme. Very cold and readable. So nice. That said, it would be really nice to see support added for nvim-cmp and Which-key.

**Comment by Aliqyan-21** [comment]
Thank you @windowsrefund! 

Sure, soon whichkey and nvim-cmp support will be added.

**Comment by Aliqyan-21** [comment]
Hey, whichkey and nvim-cmp support has been added, try and tell if you like it!

**Comment by windowsrefund** [comment]
Thanks so much for this. I just wonder if the gray works in the which-key panel?

![image](https://github.com/user-attachments/assets/9f108f44-e49b-465c-99ab-38410d46ae3b)

**Comment by Aliqyan-21** [comment]
@windowsrefund yes right I was also thinking of uniformity...to match our darkvoid minimalism.

**Comment by Aliqyan-21** [comment]
so the mistake was not including all the highlights that's given in [which key readme0](https://github.com/folke/which-key.nvim/blob/main/README.md) but now if you will see @windowsrefund it's fixed.

**Comment by windowsrefund** [comment]
Very nice. Thank you.
